<?php
/**
 * Os 150 oponentes da campanha — 30 por dificuldade.
 * Gerado a partir do documento de prompts. 'img' vazio = a arte ainda não subiu;
 * o site desenha a silhueta e continua funcionando.
 */
declare(strict_types=1);

return [
  1 => [
    ['n'=>1,'slug'=>'tuti-o-menino-do-papiro','nome'=>'Tuti, o Menino do Papiro','eixo'=>'Normais de Nível 3','img'=>'op-tuti-menino-do-papiro.png'],
    ['n'=>2,'slug'=>'ze-ankh-do-cais','nome'=>'Zé-Ankh do Cais','eixo'=>'Água / Aqua','img'=>'op-ze-ankh-do-cais.png'],
    ['n'=>3,'slug'=>'merit-a-fiandeira','nome'=>'Merit, a Fiandeira','eixo'=>'Planta / defensiva','img'=>'op-merit-fiandeira.png'],
    ['n'=>4,'slug'=>'bibi-ra-a-aprendiz-distraida','nome'=>'Bibi-Rá, a Aprendiz Distraída','eixo'=>'Luz / Fada','img'=>'op-bibi-ra-aprendiz-distraida.png'],
    ['n'=>5,'slug'=>'hori-o-padeiro-de-cevada','nome'=>'Hori, o Padeiro de Cevada','eixo'=>'Terra / Rocha','img'=>'op-hori-padeiro-de-cevada.png'],
    ['n'=>6,'slug'=>'nena-a-pastora-de-ibis','nome'=>'Nena, a Pastora de Íbis','eixo'=>'Besta Alada','img'=>'op-nena-pastora-de-ibis.png'],
    ['n'=>7,'slug'=>'kemsa-o-varredor-do-templo','nome'=>'Kemsa, o Varredor do Templo','eixo'=>'Máquina simples','img'=>'op-kemsa-varredor-do-templo.png'],
    ['n'=>8,'slug'=>'djedu-o-pescador-sonolento','nome'=>'Djedu, o Pescador Sonolento','eixo'=>'Peixe','img'=>'op-djedu-pescador-sonolento.png'],
    ['n'=>9,'slug'=>'sati-a-carregadora-dagua','nome'=>'Sati, a Carregadora d’Água','eixo'=>'Água / DEF','img'=>'op-sati-carregadora-dagua.png'],
    ['n'=>10,'slug'=>'peni-o-escriba-de-bolso','nome'=>'Peni, o Escriba de Bolso','eixo'=>'Mágicas Normais','img'=>'op-peni-escriba-de-bolso.png'],
    ['n'=>11,'slug'=>'iti-uai-o-trocador-de-figurinha','nome'=>'Iti-Uai, o Trocador de Figurinha','eixo'=>'Deck aleatório','img'=>'op-iti-uai-trocador-de-figurinha.png'],
    ['n'=>12,'slug'=>'anuka-a-menina-do-gato-torto','nome'=>'Anuka, a Menina do Gato Torto','eixo'=>'Besta','img'=>'op-anuka-menina-do-gato-torto.png'],
    ['n'=>13,'slug'=>'nakht-o-ajudante-do-barbeiro','nome'=>'Nakht, o Ajudante do Barbeiro','eixo'=>'Guerreiro fraco','img'=>'op-nakht-ajudante-do-barbeiro.png'],
    ['n'=>14,'slug'=>'reni-a-colhedora-de-tamaras','nome'=>'Reni, a Colhedora de Tâmaras','eixo'=>'Planta','img'=>'op-reni-colhedora-de-tamaras.png'],
    ['n'=>15,'slug'=>'sebo-o-cavador-de-poco','nome'=>'Sebo, o Cavador de Poço','eixo'=>'Rocha','img'=>'op-sebo-cavador-de-poco.png'],
    ['n'=>16,'slug'=>'tia-nefer-da-feira','nome'=>'Tia Nefer da Feira','eixo'=>'Mágicas de cura','img'=>'op-tia-nefer-da-feira.png'],
    ['n'=>17,'slug'=>'kaka-amon-o-curioso','nome'=>'Kaká-Amon, o Curioso','eixo'=>'Efeito de Virar','img'=>'op-kaka-amon-curioso.png'],
    ['n'=>18,'slug'=>'meri-a-contadora-de-graos','nome'=>'Meri, a Contadora de Grãos','eixo'=>'Contagem / Deck fino','img'=>'op-meri-contadora-de-graos.png'],
    ['n'=>19,'slug'=>'huy-o-tocador-de-flauta-de-junco','nome'=>'Huy, o Tocador de Flauta de Junco','eixo'=>'Vento','img'=>'op-huy-tocador-de-flauta-de-junco.png'],
    ['n'=>20,'slug'=>'bastita-a-domadora-de-gatinhos','nome'=>'Bastita, a Domadora de Gatinhos','eixo'=>'Besta enxame','img'=>'op-bastita-domadora-de-gatinhos.png'],
    ['n'=>21,'slug'=>'ptahzinho-o-aprendiz-de-oleiro','nome'=>'Ptahzinho, o Aprendiz de Oleiro','eixo'=>'Rocha / Terra','img'=>'op-ptahzinho-aprendiz-de-oleiro.png'],
    ['n'=>22,'slug'=>'nubi-a-tecela-de-esteira','nome'=>'Nubi, a Tecelã de Esteira','eixo'=>'DEF alta','img'=>'op-nubi-tecela-de-esteira.png'],
    ['n'=>23,'slug'=>'seti-cadete-o-guarda-novato','nome'=>'Seti Cadete, o Guarda Novato','eixo'=>'Guerreiro','img'=>'op-seti-cadete-guarda-novato.png'],
    ['n'=>24,'slug'=>'aya-a-vendedora-de-amuleto-falso','nome'=>'Aya, a Vendedora de Amuleto Falso','eixo'=>'Mágica de Equipamento','img'=>'op-aya-vendedora-de-amuleto-falso.png'],
    ['n'=>25,'slug'=>'ronco-re-o-vigia-que-dorme','nome'=>'Ronco-Ré, o Vigia que Dorme','eixo'=>'Deck de espera','img'=>'op-ronco-re-vigia-que-dorme.png'],
    ['n'=>26,'slug'=>'tuia-a-menina-do-espelho-de-bronze','nome'=>'Tuia, a Menina do Espelho de Bronze','eixo'=>'Cópia / Luz','img'=>'op-tuia-menina-do-espelho-de-bronze.png'],
    ['n'=>27,'slug'=>'ib-o-menino-sem-deck','nome'=>'Ib, o Menino Sem Deck','eixo'=>'40 Normais idênticos','img'=>'op-ib-menino-sem-deck.png'],
    ['n'=>28,'slug'=>'nefertitica-a-que-so-copia','nome'=>'Nefertitica, a Que Só Copia','eixo'=>'Espelho do seu D1','img'=>'op-nefertitica-que-so-copia.png'],
    ['n'=>29,'slug'=>'hapi-junior-o-barqueiro-aprendiz','nome'=>'Hapi Júnior, o Barqueiro Aprendiz','eixo'=>'Água / Serpente Marinha','img'=>'op-hapi-junior-barqueiro-aprendiz.png'],
    ['n'=>30,'slug'=>'mut-a-avo-do-oasis','nome'=>'Mut, a Avó do Oásis','eixo'=>'Todos os tipos, 1 de cada','img'=>'op-mut-avo-do-oasis.png'],
  ],
  2 => [
    ['n'=>1,'slug'=>'rekh-o-cameleiro-de-bronze','nome'=>'Rekh, o Cameleiro de Bronze','eixo'=>'Besta / Nível 4','img'=>''],
    ['n'=>2,'slug'=>'sena-a-cambista-de-contas','nome'=>'Sena, a Cambista de Contas','eixo'=>'Economia / compra','img'=>''],
    ['n'=>3,'slug'=>'amosis-o-guarda-de-portao','nome'=>'Amosis, o Guarda de Portão','eixo'=>'Guerreiro DEF','img'=>''],
    ['n'=>4,'slug'=>'kiya-a-perfumista-ambulante','nome'=>'Kiya, a Perfumista Ambulante','eixo'=>'Mágica Contínua','img'=>''],
    ['n'=>5,'slug'=>'bakenu-o-domador-de-escaravelho','nome'=>'Bakenu, o Domador de Escaravelho','eixo'=>'Inseto','img'=>''],
    ['n'=>6,'slug'=>'tetisheri-a-costureira-de-bandeiras','nome'=>'Tetisheri, a Costureira de Bandeiras','eixo'=>'Equipamento','img'=>''],
    ['n'=>7,'slug'=>'nub-kau-o-batedor-de-cobre','nome'=>'Nub-Kau, o Batedor de Cobre','eixo'=>'Máquina','img'=>''],
    ['n'=>8,'slug'=>'iras-a-cartomante-de-beira-de-estrada','nome'=>'Iras, a Cartomante de Beira de Estrada','eixo'=>'Adivinhação / topo do Deck','img'=>''],
    ['n'=>9,'slug'=>'khaemu-o-puxador-de-corda','nome'=>'Khaemu, o Puxador de Corda','eixo'=>'Tributo','img'=>''],
    ['n'=>10,'slug'=>'zeze-sekhem-o-malabarista','nome'=>'Zezé-Sekhem, o Malabarista','eixo'=>'Mágica Rápida','img'=>''],
    ['n'=>11,'slug'=>'ipuy-o-entalhador-de-amuleto','nome'=>'Ipuy, o Entalhador de Amuleto','eixo'=>'Equipamento / Terra','img'=>''],
    ['n'=>12,'slug'=>'hetep-a-cozinheira-da-caravana','nome'=>'Hetep, a Cozinheira da Caravana','eixo'=>'Cura / vida','img'=>''],
    ['n'=>13,'slug'=>'ranefer-o-rapaz-das-mulas','nome'=>'Ranefer, o Rapaz das Mulas','eixo'=>'Enxame Nível 3','img'=>''],
    ['n'=>14,'slug'=>'sitre-a-contadora-de-estrelas','nome'=>'Sitre, a Contadora de Estrelas','eixo'=>'Luz','img'=>''],
    ['n'=>15,'slug'=>'menna-o-fiscal-de-grao','nome'=>'Menna, o Fiscal de Grão','eixo'=>'Contagem / trava','img'=>''],
    ['n'=>16,'slug'=>'ta-uai-a-que-vende-agua-cara','nome'=>'Ta-Uai, a Que Vende Água Cara','eixo'=>'Água / custo','img'=>''],
    ['n'=>17,'slug'=>'paser-o-coveiro-falante','nome'=>'Paser, o Coveiro Falante','eixo'=>'Cemitério','img'=>''],
    ['n'=>18,'slug'=>'nebet-a-cuidadora-de-falcoes','nome'=>'Nebet, a Cuidadora de Falcões','eixo'=>'Besta Alada','img'=>''],
    ['n'=>19,'slug'=>'djehuti-bao-o-apostador','nome'=>'Djehuti-Bão, o Apostador','eixo'=>'Sorte / moeda e dado','img'=>''],
    ['n'=>20,'slug'=>'renenu-a-encantadora-de-rato','nome'=>'Renenu, a Encantadora de Rato','eixo'=>'Besta enxame','img'=>''],
    ['n'=>21,'slug'=>'sobeko-o-vigia-do-vau','nome'=>'Sobeko, o Vigia do Vau','eixo'=>'Réptil','img'=>''],
    ['n'=>22,'slug'=>'ahmose-o-corredor-de-recado','nome'=>'Ahmose, o Corredor de Recado','eixo'=>'Velocidade','img'=>''],
    ['n'=>23,'slug'=>'merira-a-curandeira-de-feira','nome'=>'Merira, a Curandeira de Feira','eixo'=>'Mágica / recuperação','img'=>''],
    ['n'=>24,'slug'=>'panehsy-o-mercador-de-sandalia','nome'=>'Panehsy, o Mercador de Sandália','eixo'=>'Equipamento','img'=>''],
    ['n'=>25,'slug'=>'khu-o-menino-que-cresceu','nome'=>'Khu, o Menino que Cresceu','eixo'=>'O Deck do Tuti, evoluído','img'=>''],
    ['n'=>26,'slug'=>'iset-mina-a-cantadora-de-modinha','nome'=>'Iset-Mina, a Cantadora de Modinha','eixo'=>'Mágica Contínua','img'=>''],
    ['n'=>27,'slug'=>'amenu-o-ferreiro-de-bronze','nome'=>'Amenu, o Ferreiro de Bronze','eixo'=>'Guerreiro / Equipamento','img'=>''],
    ['n'=>28,'slug'=>'tjaru-o-barqueiro-rabugento','nome'=>'Tjaru, o Barqueiro Rabugento','eixo'=>'Água / trava','img'=>''],
    ['n'=>29,'slug'=>'nefru-a-colecionadora-de-conchas','nome'=>'Nefru, a Colecionadora de Conchas','eixo'=>'Aqua / Serpente Marinha','img'=>''],
    ['n'=>30,'slug'=>'wenis-o-escriba-reprovado','nome'=>'Wenis, o Escriba Reprovado','eixo'=>'Armadilha Normal','img'=>''],
  ],
  3 => [
    ['n'=>1,'slug'=>'horemheb-o-capitao-de-escudo','nome'=>'Horemheb, o Capitão de Escudo','eixo'=>'Guerreiro DEF alta','img'=>'op-horemheb-capitao-de-escudo.png'],
    ['n'=>2,'slug'=>'neferet-a-sacerdotisa-de-turno','nome'=>'Neferet, a Sacerdotisa de Turno','eixo'=>'Luz / Fada','img'=>'op-neferet-sacerdotisa-de-turno.png'],
    ['n'=>3,'slug'=>'kamose-o-arqueiro-de-sicomoro','nome'=>'Kamose, o Arqueiro de Sicômoro','eixo'=>'Vento / ataque direto','img'=>'op-kamose-arqueiro-de-sicomoro.png'],
    ['n'=>4,'slug'=>'isetnofret-a-guardia-do-portal','nome'=>'Isetnofret, a Guardiã do Portal','eixo'=>'Armadilha Contínua','img'=>'op-isetnofret-guardia-do-portal.png'],
    ['n'=>5,'slug'=>'pashed-o-lanceiro-do-vau','nome'=>'Pashed, o Lanceiro do Vau','eixo'=>'Água / Guerreiro','img'=>'op-pashed-lanceiro-do-vau.png'],
    ['n'=>6,'slug'=>'tia-a-leitora-de-entranhas','nome'=>'Tia, a Leitora de Entranhas','eixo'=>'Cemitério / topo do Deck','img'=>'op-tia-leitora-de-entranhas.png'],
    ['n'=>7,'slug'=>'userhat-o-domador-de-leao','nome'=>'Userhat, o Domador de Leão','eixo'=>'Besta / ATK alto','img'=>'op-userhat-domador-de-leao.png'],
    ['n'=>8,'slug'=>'merneith-a-cavaleira-de-areia','nome'=>'Merneith, a Cavaleira de Areia','eixo'=>'Velocidade / Terra','img'=>'op-merneith-cavaleira-de-areia.png'],
    ['n'=>9,'slug'=>'bakenkhons-o-sacerdote-de-segunda','nome'=>'Bakenkhons, o Sacerdote de Segunda','eixo'=>'Ritual iniciante','img'=>'op-bakenkhons-sacerdote-de-segunda.png'],
    ['n'=>10,'slug'=>'sennedjem-o-pintor-de-tumba','nome'=>'Sennedjem, o Pintor de Tumba','eixo'=>'Ilusão / cópia','img'=>'op-sennedjem-pintor-de-tumba.png'],
    ['n'=>11,'slug'=>'iuty-a-espadachim-de-ebano','nome'=>'Iuty, a Espadachim de Ébano','eixo'=>'Guerreiro / Equipamento','img'=>'op-iuty-espadachim-de-ebano.png'],
    ['n'=>12,'slug'=>'ptahmose-o-guardiao-de-chave','nome'=>'Ptahmose, o Guardião de Chave','eixo'=>'Trava / Mágica Contínua','img'=>'op-ptahmose-guardiao-de-chave.png'],
    ['n'=>13,'slug'=>'nebamon-o-cacador-do-delta','nome'=>'Nebamon, o Caçador do Delta','eixo'=>'Besta Alada / Inseto','img'=>'op-nebamon-cacador-do-delta.png'],
    ['n'=>14,'slug'=>'henut-a-sentinela-da-noite','nome'=>'Henut, a Sentinela da Noite','eixo'=>'Trevas','img'=>'op-henut-sentinela-da-noite.png'],
    ['n'=>15,'slug'=>'roma-o-sargento-de-obelisco','nome'=>'Roma, o Sargento de Obelisco','eixo'=>'Rocha / DEF','img'=>'op-roma-sargento-de-obelisco.png'],
    ['n'=>16,'slug'=>'tayuhenut-a-voz-do-templo','nome'=>'Tayuhenut, a Voz do Templo','eixo'=>'Mágica Rápida','img'=>'op-tayuhenut-voz-do-templo.png'],
    ['n'=>17,'slug'=>'khonsu-bao-o-vigia-da-lua','nome'=>'Khonsu-Bão, o Vigia da Lua','eixo'=>'Luz / Trevas','img'=>'op-khonsu-bao-vigia-da-lua.png'],
    ['n'=>18,'slug'=>'ineni-o-arquiteto-de-muro','nome'=>'Ineni, o Arquiteto de Muro','eixo'=>'DEF / trava','img'=>'op-ineni-arquiteto-de-muro.png'],
    ['n'=>19,'slug'=>'sitamun-a-cavadora-de-cripta','nome'=>'Sitamun, a Cavadora de Cripta','eixo'=>'Zumbi','img'=>'op-sitamun-cavadora-de-cripta.png'],
    ['n'=>20,'slug'=>'amenemhat-o-instrutor-de-duelo','nome'=>'Amenemhat, o Instrutor de Duelo','eixo'=>'Deck-modelo do PDF','img'=>'op-amenemhat-instrutor-de-duelo.png'],
    ['n'=>21,'slug'=>'wadjmose-o-portador-de-estandarte','nome'=>'Wadjmose, o Portador de Estandarte','eixo'=>'Enxame / Vento','img'=>'op-wadjmose-portador-de-estandarte.png'],
    ['n'=>22,'slug'=>'nubkhaes-a-mestra-de-falcoaria','nome'=>'Nubkhaes, a Mestra de Falcoaria','eixo'=>'Besta Alada avançado','img'=>'op-nubkhaes-mestra-de-falcoaria.png'],
    ['n'=>23,'slug'=>'djeserka-o-domador-de-hipopotamo','nome'=>'Djeserka, o Domador de Hipopótamo','eixo'=>'Besta / Tributo','img'=>'op-djeserka-domador-de-hipopotamo.png'],
    ['n'=>24,'slug'=>'nefertari-mina-a-escriba-de-guerra','nome'=>'Nefertari-Mina, a Escriba de Guerra','eixo'=>'Armadilha de Resposta','img'=>'op-nefertari-mina-escriba-de-guerra.png'],
    ['n'=>25,'slug'=>'setau-o-encantador-de-naja','nome'=>'Setau, o Encantador de Naja','eixo'=>'Réptil / veneno','img'=>'op-setau-encantador-de-naja.png'],
    ['n'=>26,'slug'=>'henuttawy-a-guardia-do-rio','nome'=>'Henuttawy, a Guardiã do Rio','eixo'=>'Água / Serpente Marinha','img'=>'op-henuttawy-guardia-do-rio.png'],
    ['n'=>27,'slug'=>'paneb-o-brigao-do-alojamento','nome'=>'Paneb, o Brigão do Alojamento','eixo'=>'Guerreiro / ATK direto','img'=>'op-paneb-brigao-do-alojamento.png'],
    ['n'=>28,'slug'=>'meryt-ra-a-astronoma-de-plantao','nome'=>'Meryt-Rá, a Astrônoma de Plantão','eixo'=>'Luz / manipulação de compra','img'=>'op-meryt-ra-astronoma-de-plantao.png'],
    ['n'=>29,'slug'=>'sebek-iri-o-barqueiro-dos-mortos','nome'=>'Sebek-Iri, o Barqueiro dos Mortos','eixo'=>'Zumbi / Cemitério','img'=>'op-sebek-iri-barqueiro-dos-mortos.png'],
    ['n'=>30,'slug'=>'kha-o-mestre-de-obras','nome'=>'Kha, o Mestre de Obras','eixo'=>'Máquina / Fusão','img'=>'op-kha-mestre-de-obras.png'],
  ],
  4 => [
    ['n'=>1,'slug'=>'vizir-ramose-o-cobrador-de-impostos','nome'=>'Vizir Ramosé, o Cobrador de Impostos','eixo'=>'Custo / pagamento de PV','img'=>'op-vizir-ramose-cobrador-de-impostos.png'],
    ['n'=>2,'slug'=>'grande-sacerdotisa-ahhotep','nome'=>'Grande Sacerdotisa Ahhotep','eixo'=>'Luz / Ritual','img'=>'op-grande-sacerdotisa-ahhotep.png'],
    ['n'=>3,'slug'=>'general-piye-uai-o-quebra-linhas','nome'=>'General Piye-Uai, o Quebra-Linhas','eixo'=>'Guerreiro / ataque múltiplo','img'=>'op-general-piye-uai-quebra-linhas.png'],
    ['n'=>4,'slug'=>'princesa-meritamon-a-entediada','nome'=>'Princesa Meritamon, a Entediada','eixo'=>'Controle / negação','img'=>'op-princesa-meritamon-entediada.png'],
    ['n'=>5,'slug'=>'tesoureiro-senenmut-o-que-anota-tudo','nome'=>'Tesoureiro Senenmut, o Que Anota Tudo','eixo'=>'Contagem / Deck fino','img'=>'op-tesoureiro-senenmut-que-anota-tudo.png'],
    ['n'=>6,'slug'=>'comandante-neferhotep-o-muro','nome'=>'Comandante Neferhotep, o Muro','eixo'=>'DEF extrema','img'=>'op-comandante-neferhotep-muro.png'],
    ['n'=>7,'slug'=>'duquesa-tiye-das-pedras','nome'=>'Duquesa Tiye das Pedras','eixo'=>'Rocha / Terra','img'=>'op-duquesa-tiye-das-pedras.png'],
    ['n'=>8,'slug'=>'chanceler-hapuseneb-o-frio','nome'=>'Chanceler Hapuseneb, o Frio','eixo'=>'Armadilha de Resposta','img'=>'op-chanceler-hapuseneb-frio.png'],
    ['n'=>9,'slug'=>'alta-sacerdotisa-karomama','nome'=>'Alta Sacerdotisa Karomama','eixo'=>'Ritual duplo','img'=>'op-alta-sacerdotisa-karomama.png'],
    ['n'=>10,'slug'=>'arquiteto-imhotepe-bao','nome'=>'Arquiteto Imhotepe-Bão','eixo'=>'Máquina / construção','img'=>'op-arquiteto-imhotepe-bao.png'],
    ['n'=>11,'slug'=>'principe-uadjmose-o-herdeiro-invicto','nome'=>'Príncipe Uadjmose, o Herdeiro Invicto','eixo'=>'Deck de campeão','img'=>'op-principe-uadjmose-herdeiro-invicto.png'],
    ['n'=>12,'slug'=>'mestre-djedptah-o-fusionista','nome'=>'Mestre Djedptah, o Fusionista','eixo'=>'Fusão','img'=>'op-mestre-djedptah-fusionista.png'],
    ['n'=>13,'slug'=>'dama-nofret-do-leque','nome'=>'Dama Nofret do Leque','eixo'=>'Vento / posição','img'=>'op-dama-nofret-do-leque.png'],
    ['n'=>14,'slug'=>'sumo-escriba-tjanuni','nome'=>'Sumo Escriba Tjanuni','eixo'=>'Trava de Mágica','img'=>'op-sumo-escriba-tjanuni.png'],
    ['n'=>15,'slug'=>'general-nakhtmin-o-cerco','nome'=>'General Nakhtmin, o Cerco','eixo'=>'Trava / DEF + queima','img'=>'op-general-nakhtmin-cerco.png'],
    ['n'=>16,'slug'=>'baronesa-isetemkheb','nome'=>'Baronesa Isetemkheb','eixo'=>'Veneno / dano contínuo','img'=>'op-baronesa-isetemkheb.png'],
    ['n'=>17,'slug'=>'marechal-herihor-o-fogo-lento','nome'=>'Marechal Herihor, o Fogo Lento','eixo'=>'Piro','img'=>'op-marechal-herihor-fogo-lento.png'],
    ['n'=>18,'slug'=>'sacerdote-pinedjem-o-ritualista','nome'=>'Sacerdote Pinedjem, o Ritualista','eixo'=>'Ritual + tributo','img'=>'op-sacerdote-pinedjem-ritualista.png'],
    ['n'=>19,'slug'=>'condessa-neskhons-a-venenosa','nome'=>'Condessa Neskhons, a Venenosa','eixo'=>'Réptil','img'=>'op-condessa-neskhons-venenosa.png'],
    ['n'=>20,'slug'=>'almirante-wenamon-do-delta','nome'=>'Almirante Wenamon do Delta','eixo'=>'Água / Serpente Marinha','img'=>'op-almirante-wenamon-do-delta.png'],
    ['n'=>21,'slug'=>'guardia-sitre-in-a-ama-real','nome'=>'Guardiã Sitre-In, a Ama Real','eixo'=>'Cura / proteção','img'=>'op-guardia-sitre-in-ama-real.png'],
    ['n'=>22,'slug'=>'mago-da-corte-setnakht','nome'=>'Mago da Corte Setnakht','eixo'=>'Mágica pura','img'=>'op-mago-da-corte-setnakht.png'],
    ['n'=>23,'slug'=>'dama-maatkare-a-balanca-viva','nome'=>'Dama Maatkare, a Balança Viva','eixo'=>'Equilíbrio / ATK-DEF','img'=>'op-dama-maatkare-balanca-viva.png'],
    ['n'=>24,'slug'=>'governador-panehesy-do-sul','nome'=>'Governador Panehesy do Sul','eixo'=>'Terra / Besta-Guerreira','img'=>'op-governador-panehesy-do-sul.png'],
    ['n'=>25,'slug'=>'sacerdotisa-shepenupet-a-muda','nome'=>'Sacerdotisa Shepenupet, a Muda','eixo'=>'Negação de efeito','img'=>'op-sacerdotisa-shepenupet-muda.png'],
    ['n'=>26,'slug'=>'mestre-de-armas-bakenranef','nome'=>'Mestre de Armas Bakenranef','eixo'=>'Equipamento em série','img'=>'op-mestre-de-armas-bakenranef.png'],
    ['n'=>27,'slug'=>'vizir-nespaqashuty-o-paciente','nome'=>'Vizir Nespaqashuty, o Paciente','eixo'=>'Deck de estafa','img'=>'op-vizir-nespaqashuty-paciente.png'],
    ['n'=>28,'slug'=>'rainha-regente-katimala','nome'=>'Rainha-Regente Katimala','eixo'=>'Deck completo','img'=>'op-rainha-regente-katimala.png'],
    ['n'=>29,'slug'=>'escriba-mor-amenemope-o-proverbio','nome'=>'Escriba-Mor Amenemope, o Provérbio','eixo'=>'Contra-jogo','img'=>'op-escriba-mor-amenemope-proverbio.png'],
    ['n'=>30,'slug'=>'campeao-real-sishaq-o-invicto-do-patio','nome'=>'Campeão Real Sishaq, o Invicto do Pátio','eixo'=>'Assinatura / o melhor Deck do nível','img'=>'op-campeao-real-sishaq-invicto-do-patio.png'],
  ],
  5 => [
    ['n'=>1,'slug'=>'anubis-uai-o-pesador-de-coracoes','nome'=>'Anubis-Uai, o Pesador de Corações','eixo'=>'Balança / ATK-DEF','img'=>'op-anubis-uai-pesador-de-coracoes.png'],
    ['n'=>2,'slug'=>'a-devoradora-ammit-mina','nome'=>'A Devoradora Ammit-Mina','eixo'=>'Destruição / Cemitério','img'=>'op-devoradora-ammit-mina.png'],
    ['n'=>3,'slug'=>'ka-sem-nome-o-duplo-perdido','nome'=>'Ka-Sem-Nome, o Duplo Perdido','eixo'=>'Cópia do seu Deck','img'=>'op-ka-sem-nome-duplo-perdido.png'],
    ['n'=>4,'slug'=>'sacerdote-emplastrado-nefer-ka','nome'=>'Sacerdote Emplastrado Nefer-Ka','eixo'=>'Zumbi','img'=>'op-sacerdote-emplastrado-nefer-ka.png'],
    ['n'=>5,'slug'=>'a-chorona-do-nilo-negro','nome'=>'A Chorona do Nilo Negro','eixo'=>'Água / Trevas','img'=>'op-chorona-do-nilo-negro.png'],
    ['n'=>6,'slug'=>'apep-a-serpente-de-onze-voltas','nome'=>'Apep, a Serpente de Onze Voltas','eixo'=>'Serpente / trava','img'=>'op-apep-serpente-de-onze-voltas.png'],
    ['n'=>7,'slug'=>'o-barqueiro-sem-remo','nome'=>'O Barqueiro Sem Remo','eixo'=>'Trava de Fase','img'=>'op-barqueiro-sem-remo.png'],
    ['n'=>8,'slug'=>'sekhmet-vermelha-a-fome','nome'=>'Sekhmet-Vermelha, a Fome','eixo'=>'Piro / ATK direto','img'=>'op-sekhmet-vermelha-fome.png'],
    ['n'=>9,'slug'=>'o-escriba-cego-de-duat','nome'=>'O Escriba Cego de Duat','eixo'=>'Negação','img'=>'op-escriba-cego-de-duat.png'],
    ['n'=>10,'slug'=>'neith-a-tecela-de-mortalha','nome'=>'Neith, a Tecelã de Mortalha','eixo'=>'Equipamento / trava','img'=>'op-neith-tecela-de-mortalha.png'],
    ['n'=>11,'slug'=>'guardiao-de-portao-i-o-que-nao-pisca','nome'=>'Guardião de Portão I — o Que Não Pisca','eixo'=>'DEF absurda','img'=>'op-guardiao-de-portao-i-que-nao-pisca.png'],
    ['n'=>12,'slug'=>'guardiao-de-portao-ii-o-que-nao-fala','nome'=>'Guardião de Portão II — o Que Não Fala','eixo'=>'Negação de Mágica','img'=>'op-guardiao-de-portao-ii-que-nao-fala.png'],
    ['n'=>13,'slug'=>'guardiao-de-portao-iii-o-que-nao-sai','nome'=>'Guardião de Portão III — o Que Não Sai','eixo'=>'Trava de invocação','img'=>'op-guardiao-de-portao-iii-que-nao-sai.png'],
    ['n'=>14,'slug'=>'a-mumia-do-poco-seco','nome'=>'A Múmia do Poço Seco','eixo'=>'Zumbi / retorno','img'=>'op-mumia-do-poco-seco.png'],
    ['n'=>15,'slug'=>'khepri-podre-o-escaravelho-partido','nome'=>'Khepri-Podre, o Escaravelho Partido','eixo'=>'Inseto / enxame','img'=>'op-khepri-podre-escaravelho-partido.png'],
    ['n'=>16,'slug'=>'a-dama-de-alabastro-rachado','nome'=>'A Dama de Alabastro Rachado','eixo'=>'Ilusão','img'=>'op-dama-de-alabastro-rachado.png'],
    ['n'=>17,'slug'=>'set-sem-sombra','nome'=>'Set-Sem-Sombra','eixo'=>'Trevas / Vento','img'=>'op-set-sem-sombra.png'],
    ['n'=>18,'slug'=>'o-coro-de-quarenta-e-duas-vozes','nome'=>'O Coro de Quarenta e Duas Vozes','eixo'=>'Enxame / múltiplo','img'=>'op-coro-de-quarenta-e-duas-vozes.png'],
    ['n'=>19,'slug'=>'meretseger-a-que-ama-o-silencio','nome'=>'Meretseger, a Que Ama o Silêncio','eixo'=>'Trava total','img'=>'op-meretseger-que-ama-o-silencio.png'],
    ['n'=>20,'slug'=>'o-ourives-enterrado-vivo','nome'=>'O Ourives Enterrado Vivo','eixo'=>'Máquina / Equipamento','img'=>'op-ourives-enterrado-vivo.png'],
    ['n'=>21,'slug'=>'bes-desfigurado-o-riso-torto','nome'=>'Bes Desfigurado, o Riso Torto','eixo'=>'Sorte / caos','img'=>'op-bes-desfigurado-riso-torto.png'],
    ['n'=>22,'slug'=>'a-rainha-de-cabeca-trocada','nome'=>'A Rainha de Cabeça Trocada','eixo'=>'Cópia / troca de controle','img'=>'op-rainha-de-cabeca-trocada.png'],
    ['n'=>23,'slug'=>'sobek-descarnado','nome'=>'Sobek Descarnado','eixo'=>'Réptil / ATK','img'=>'op-sobek-descarnado.png'],
    ['n'=>24,'slug'=>'o-sonho-de-amset-ra','nome'=>'O Sonho de Amset-Ra','eixo'=>'Trevas / Fusão','img'=>'op-sonho-de-amset-ra.png'],
    ['n'=>25,'slug'=>'thoth-invertido-o-escriba-do-erro','nome'=>'Thoth Invertido, o Escriba do Erro','eixo'=>'Inversão de efeito','img'=>'op-thoth-invertido-escriba-do-erro.png'],
    ['n'=>26,'slug'=>'a-legiao-de-ushabti','nome'=>'A Legião de Ushabti','eixo'=>'Enxame de fichas','img'=>'op-legiao-de-ushabti.png'],
    ['n'=>27,'slug'=>'hathor-de-chifres-quebrados','nome'=>'Hathor de Chifres Quebrados','eixo'=>'Cura invertida','img'=>'op-hathor-de-chifres-quebrados.png'],
    ['n'=>28,'slug'=>'o-farao-menino-que-nao-cresceu','nome'=>'O Faraó Menino que Não Cresceu','eixo'=>'Deck completo, jogado perfeitamente','img'=>'op-farao-menino-que-nao-cresceu.png'],
    ['n'=>29,'slug'=>'nekhbet-a-abutre-mae','nome'=>'Nekhbet, a Abutre-Mãe','eixo'=>'Besta Alada / Trevas','img'=>'op-nekhbet-abutre-mae.png'],
    ['n'=>30,'slug'=>'o-espelho-de-amset-ra','nome'=>'O Espelho de Amset-Ra','eixo'=>'**O SEU PRÓPRIO DECK**','img'=>'op-espelho-de-amset-ra.png'],
  ],
];
